#! /bin/sh

#     _         _            _             _   
#    / \  _   _| |_ ___  ___| |_ __ _ _ __| |_ 
#   / _ \| | | | __/ _ \/ __| __/ _` | '__| __|
#  / ___ \ |_| | || (_) \__ \ || (_| | |  | |_ 
# /_/   \_\__,_|\__\___/|___/\__\__,_|_|   \__|
#  ____                                       
# |  _ \  __ _  ___ _ __ ___   ___  _ __  ___ 
# | | | |/ _` |/ _ \ '_ ` _ \ / _ \| '_ \/ __|
# | |_| | (_| |  __/ | | | | | (_) | | | \__ \
# |____/ \__,_|\___|_| |_| |_|\___/|_| |_|___/

# setting the wallpaper
nitrogen --restore &
# compositor
picom -f &
# shortcut daemon
pgrep -x sxhkd > /dev/null || sxhkd &
# polybar
$HOME/.config/polybar/launch.sh &

#  ____  _           _             
# |  _ \(_)___ _ __ | | __ _ _   _ 
# | | | | / __| '_ \| |/ _` | | | |
# | |_| | \__ \ |_) | | (_| | |_| |
# |____/|_|___/ .__/|_|\__,_|\__, |
#             |_|            |___/
bspc monitor -d I II III IV V VI VII VIII IX X

#   ____             __ _       
#  / ___|___  _ __  / _(_) __ _ 
# | |   / _ \| '_ \| |_| |/ _` |
# | |__| (_) | | | |  _| | (_| |
#  \____\___/|_| |_|_| |_|\__, |
#                         |___/
bspc config border_width       2.5 
bspc config window_gap		    10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# __        ___           _                 ____        _           
# \ \      / (_)_ __   __| | _____      __ |  _ \ _   _| | ___  ___ 
#  \ \ /\ / /| | '_ \ / _` |/ _ \ \ /\ / / | |_) | | | | |/ _ \/ __|
#   \ V  V / | | | | | (_| | (_) \ V  V /  |  _ <| |_| | |  __/\__ \
#    \_/\_/  |_|_| |_|\__,_|\___/ \_/\_/   |_| \_\\__,_|_|\___||___/
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#     _         _            _             _   
#    / \  _   _| |_ ___  ___| |_ __ _ _ __| |_ 
#   / _ \| | | | __/ _ \/ __| __/ _` | '__| __|
#  / ___ \ |_| | || (_) \__ \ || (_| | |  | |_ 
# /_/   \_\__,_|\__\___/|___/\__\__,_|_|   \__|
#     _                    
#    / \   _ __  _ __  ___ 
#   / _ \ | '_ \| '_ \/ __|
#  / ___ \| |_) | |_) \__ \
# /_/   \_\ .__/| .__/|___/
#         |_|   |_| 

discord &