#! /bin/sh
#
#  ____ ____  ______        ____  __ ____   ____ 
# | __ ) ___||  _ \ \      / /  \/  |  _ \ / ___|
# |  _ \___ \| |_) \ \ /\ / /| |\/| | |_) | |    
# | |_) |__) |  __/ \ V  V / | |  | |  _ <| |___ 
# |____/____/|_|     \_/\_/  |_|  |_|_| \_\\____|
#

#####################
# AUTOSTART DAEMONS #
#####################

# shortcut daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# wallpaper
nitrogen --restore &

# compositor
picom -b --experimental-backends &

# polybar
$HOME/.config/polybar/launch.sh &

# xsettigs daemon
xsettingsd &

###########################
# MONITORS AND WORKSPACES #
###########################

# primary 1440p acer monitor
bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9 0

# secondary 1440p dell monitor
# bspc monitor DP-0.8 -d 8 9 0

#############
# WM CONFIG #
#############

# window spawning
bspc automatic_scheme alternate
bspc initial_polarity first_child
bspc config split_ratio 0.5

# borders, paddings and gaps
bspc config borderless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "#FFFFFF"
bspc config focused_border_color "#ebcb8b"
bspc config presel_feedback_color "#FFFFFF"

bspc config border_width 2
bspc config window_gap 10

bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

# furhter monitor config
bspc remove_unplugged_monitors true

######################
# WINDOW SPAWN RULES #
######################

bspc rule -a discord desktop='^3'

##################
# AUTOSTART APPS #
##################

#discord &
flameshot &

#######################################
# NZXT lighting and fan control setup #
#######################################

# NZXT Kraken
liquidctl --product 0x2007 set pump speed 50 &
liquidctl --product 0x2007 set ring color fixed ff0000 &
liquidctl --product 0x2007 set logo color fixed ffffff &

# Front RGB fans (color only)
liquidctl --product 0x2006 set led2 color fixed 555555 &

# Top 140mm fan
liquidctl --product 0x2006 set fan2 speed 50 &

# Back 120mm fan
liquidctl --product 0x2006 set fan3 speed 50 &

# Top LED Strip
liquidctl --product 0x2006 set led1 color fixed 000000 &

#################
# MISCELLANEOUS #
#################

# fix the cursor default
xsetroot -cursor_name left_ptr &

